# @package _group_
model_trainer:
  _target_: mbrl.models.ModelTrainer
wrapper:
  _target_: mbrl.models.OneDTransitionRewardModel
model:
  _target_: src.model.factored_grid_model.FactoredGaussianMLP
  device: ${device}
  num_layers: 2 #4
  in_size: ???
  out_size: ???
  ensemble_size: 1 #7
  hid_size: 50 #200
  deterministic: false
  propagation_method: random_model
  learn_logvar_bounds: false  # so far this works better
  activation_fn_cfg:
    _target_: torch.nn.SiLU