# @package _group_
model_trainer:
  _target_: src.util.model_trainer.MultiModelsTrainer
model:
  _target_: src.model.simple.FactoredSimple
  device: ${device}
  num_layers: 2 #4
  in_size: ???
  out_size: ???
  hid_size: 100 #200
  activation_fn_cfg: #null
    _target_: torch.nn.SiLU
  factors: ???
  reward_factors: null