# @package _group_
_target_: factored_models.grid_models.FactoredGaussianMLP
device: ${device}
num_layers: 1 #4
in_size: ???
out_size: ???
ensemble_size: 1 #7
hid_size: 50 #200
deterministic: false
propagation_method: random_model
learn_logvar_bounds: false  # so far this works better
activation_fn_cfg:
  _target_: torch.nn.SiLU