# @package _group_
model_trainer:
  _target_: src.util.model_trainer.ModelTrainerOverriden
  optim_lr: 0.05
  weight_decay: 0.
model:
  _target_: src.model.gaussian_process.FactoredMultiOutputGP
  device: ${device}
  in_size: ???
  out_size: ???
  mean: Linear
  kernel: Matern
  scale_kernel: true
  factors: ???
  reward_factors: null

batch_size: 800 #${overrides.dataset_size}