# @package _group_
model_trainer:
  _target_: src.util.model_trainer.ModelTrainerOverriden
  optim_lr: 0.0001
  weight_decay: 0.00001
model:
  _target_: src.model.neural_network.FFNN
  device: ${device}
  num_layers: 2 #4
  in_size: ???
  out_size: ???
  hid_size: 100 #200
  activation_fn_cfg: #null
    _target_: torch.nn.SiLU