# @package _group_
model_trainer:
  _target_: src.util.model_trainer.ModelTrainerOverriden
model:
  _target_: src.model.gaussian_process.MultiOutputGP
  device: ${device}
  in_size: ???
  out_size: ???
  mean: null
  kernel: null #Matern
  scale_kernel: true
  eval_metric: MSE #TODO: Better if in model trainer

batch_size: ${overrides.dataset_size}
model_lr: 0.1
model_wd: 0