# @package _group_
model_trainer:
  _target_: src.util.model_trainer.ModelTrainerOverriden
model:
  _target_: src.model.simple.Simple
  device: ${device}
  in_size: ???
  out_size: ???
  mean: null
  kernel: null