# @package _group_
model_trainer:
  _target_: src.util.model_trainer.LassoModelTrainer
  optim_lr: 0.0001
  weight_decay: 0.00001
  lambda_start: 0.
  lambda_max: 50.
  lambda_step: 0.3
  num_pretraining_epochs: 50
  take_best_factors: 2 #int|null
  theta_tol: 0.01
  reinit: false
model:
  _target_: src.model.lasso_net.LassoSimple
  device: ${device}
  num_layers: 2
  in_size: ???
  out_size: ???
  hid_size: 50
  activation_fn_cfg:
    _target_: torch.nn.SiLU
  groups: null #Not sure what it is for now ?? TODO
  dropout: false #keep as flase for now
  gamma: 0.0
  gamma_skip: 0.0
  M: 1.0