# @package _group_
model_trainer:
  _target_: src.model.lasso_net.LassoModelTrainer
  lambda_start: 0.001
wrapper:
  _target_: src.model.lasso_net.LassoOneDTransitionRewardModel
model:
  _target_: src.model.lasso_net.LassoNetGaussianMLP
  device: ${device}
  num_layers: 2 #4
  in_size: ???
  out_size: ???
  ensemble_size: 1 #7
  hid_size: 50 #200
  deterministic: false
  propagation_method: random_model
  learn_logvar_bounds: false  # so far this works better
  activation_fn_cfg:
    _target_: torch.nn.SiLU
  gamma: 0.
  gamma_skip: 0.
  M: 10.