# @package _group_
model_trainer:
  _target_: src.util.model_trainer.ModelTrainerOverriden
  model_lr: 0.01
  model_wd: 0.
model:
  _target_: src.model.linear_regression.LinearRegression
  device: ${device}
  in_size: ???
  out_size: ???

batch_size: ${overrides.dataset_size}