# @package _group_
model_trainer:
  _target_: src.util.model_trainer.ModelTrainerOverriden
  optim_lr: 0.01
  weight_decay: 0.
model:
  _target_: src.model.linear_regression.LinearRegression
  device: ${device}
  in_size: ???
  out_size: ???
  logistic: false

batch_size: ${overrides.dataset_size}