# @package _group_
model_trainer:
  _target_: src.util.model_trainer.ModelTrainerOverriden
model:
  _target_: src.model.simple.Simple
  device: ${device}
  num_layers: 4
  in_size: ???
  out_size: ???
  hid_size: 200
  eval_metric: MSE #TODO: Better if in model trainer
  activation_fn_cfg: #null
    _target_: torch.nn.SiLU