# @package _group_
model_trainer:
  _target_: mbrl.models.ModelTrainer
model:
  _target_: src.model.simple.Simple
  device: ${device}
  num_layers: 4 #4
  in_size: ???
  out_size: ???
  hid_size: 200 #200
  activation_fn_cfg: #null
    _target_: torch.nn.SiLU