# @package _group_
env: "hypergrid"
learned_rewards: false #Not supported yet
trial_length: 200 #200
num_steps: 5000 #5000
render_mode: human #null|rgb_array|human

num_elites: 1 #5
model_lr: 7.5e-4
model_wd: 3e-5
model_batch_size: 64 #256
validation_ratio: 0
freq_train_model: 50
patience: 25
num_epochs_train_model: 10 #25

planning_horizon: 15
cem_num_iters: 5
cem_elite_ratio: 0.1
cem_population_size: 350
cem_alpha: 0.1
cem_clipped_normal: false