# @package _group_
env: "hypergrid"
env_config:
  step_penalty: -1
  grid_dim: 5 #2
  grid_size: 5.
  size_end_box: 1. #1.0
  step_size: 1.
  n_obstacles: null
  size_obstacles: 1
model_wrapper:
  _target_: mbrl.models.OneDTransitionRewardModel
learned_rewards: false #Not supported yet
trial_length: 100 #Max length episode
num_steps: 500000 #Number of env steps before end of training
num_episodes: 500 #Number of env episodes before end of training
render_mode: human #null|rgb_array|human
model_path: null #/mnt/c/Users/theau/OneDrive/Documents/theau_epfl/12.PDM/code/HUCRL_for_FMDP/exp/pets_adapted/wandb/hypergrid/2023.10.06/154944

#num_elites: 5
# model_lr: 7.5e-4
# model_wd: 3e-5
model_batch_size: 256
validation_ratio: 0
freq_train_model: 50
patience: ${overrides.num_epochs_train_model}
num_epochs_train_model: 25
dataset_size: ${overrides.num_steps}

planning_horizon: 30
cem_num_iters: 5
cem_elite_ratio: 0.1
cem_population_size: 350
cem_alpha: 0.1
cem_clipped_normal: false