defaults:
  - overrides: pets_bikes

env_name: ${overrides.env}
agent: good_heuristic #random
num_steps: 365 #(~2months with 8 action_per_day)
with_tracking: false
env_config: ${overrides.env_config}
render_mode: human
additional_run_name: null
  
hydra:  
  output_subdir: null
  job_logging: null  
  run:  
    dir: .