defaults:
  - algorithm: pets_adapted
  - dynamics_model: gaussian_mlp_ensemble
  - overrides: pets_hypergrid #pets_cartpole|pets_maze|pets_hypergrid
  - action_optimizer: cem
  - experiment: wandb

seed: 0
device: "cpu" #"cuda:0"
log_frequency_agent: 1000
save_video: false
debug_mode: false

experiment_dir: ${experiment.api_name}

root_dir: "./exp"
hydra:
  run:
    dir: ${root_dir}/${algorithm.name}/${experiment_dir}/${overrides.env}/${now:%Y.%m.%d}/${now:%H%M%S}

  sweep:
    dir: ${root_dir}/${algorithm.name}/${experiment_dir}/${overrides.env}/${now:%Y.%m.%d}/${now:%H%M%S}