defaults:
  - algorithm: pets_adapted
  - dynamics_model: mixture #gaussian_mlp_ensemble
  - overrides: pets_bikes_5centroid
  - action_optimizer: cem
  - experiment: wandb

seed: 0
device: "cpu" #"cuda:0"
log_frequency_agent: 1000
save_video: false
debug_mode: false

experiment_dir: ${experiment.api_name}

root_dir: "./exp"
hydra:
  run:
    dir: ${root_dir}/${experiment_dir}/${overrides.env}/${algorithm.name}/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment.run_configs.name}

  sweep:
    dir: ${root_dir}/${experiment_dir}/${overrides.env}/${algorithm.name}/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment.run_configs.name}