defaults:
  - algorithm: pets_adapted
  - dynamics_model: simple
  - overrides: pets_bikes
  - action_optimizer: cem
  - experiment: wandb

seed: 0
device: "cpu" #"cuda:0"
additional_run_name: null
debug_mode: false

dataset_size: ${overrides.dataset_size}
model_batch_size: 128
validation_ratio: 0.2
num_epochs_train_model: 10
# bootstrap_permutes: 
# patience: null
# improvement_threshold: null

hydra:  
  output_subdir: null
  job_logging: null  
  run:  
    dir: .