defaults:
  - action_optimizer: cem
  - algorithm: pets_adapted
  - dynamics_model: gaussian_process #gaussian_process|simple|gaussian_mlp_ensemble
  - overrides: pets_hypergrid #pets_bikes
  - experiment: wandb

seed: 0
device: "cpu" #"cuda:0"
run_name: hypergrid_test_gp
debug_mode: true
silent: false

dataset_folder_name: datasets
dataset_size: 10000
model_batch_size: 256
validation_ratio: 0.2
num_epochs_train_model: 10000
patience: ${num_epochs_train_model}
learned_rewards: False
# bootstrap_permutes: 
# improvement_threshold: null

experiment_dir: ${experiment.api_name}

root_dir: "./exp"
hydra:
  run:
    dir: ${root_dir}/${experiment_dir}/${overrides.env}/train_model/${now:%Y.%m.%d}/${now:%H%M%S}_${run_name}

  sweep:
    dir: ${root_dir}/${experiment_dir}/${overrides.env}/train_model/${now:%Y.%m.%d}/${now:%H%M%S}_${run_name}